### ISSUE TITLE
Ability to differentiate between insert/extract storage priorities

### ISSUE THREAD

**Issue by raoulvdberge** [refinedmods/refinedstorage2#124]
Do we have to differentiate between insert/extract?
Currently: insert/extract on highest priority first.
Requested: insert on highest priority first, extract on lowest first.
Otherwise: two explicit priorities for insert/extract?

**Comment by hvdklauw** [comment]
The reason to insert into high priority and extract from low priority first is that it automatically defragments your network.

Sta you have storage drawers and a drive, if the storage drawer becomes full extra items go into your drive. Then by using said item the ones from the drive get used first this clearing the drive.

Otherwise you have to regularly check your drives to see if they contain items that could go somewhere else and move them by hand.

**Comment by adroslice** [comment]
Id love to have separate priorities - I think that the variant under "Requested" wouldn't be intuitive for most users of the mod.
Currently to mitigate the issues caused by having the same insert/extract priorities, I usually have universal (disk) storage on high priority, and specific (external) storage on low priority on extract only. This ensures that items from universal storage get used first, and as long as I don't use interfaces or importers for specific storage, which I normally don't, that works fine.

I think the best solution that would satisfy all would be to leave the default behavior as-is, but have a toggle hiding some more options (as to not overwhelm new players). There, you could have the default option, the extract-inverted option, and a "custom" option where you could specify both. Those details are of course just a suggestion.

**Comment by raoulvdberge** [comment]
> I think the best solution that would satisfy all would be to leave the default behavior as-is, but have a toggle hiding some more options (as to not overwhelm new players). There, you could have the default option, the extract-inverted option, and a "custom" option where you could specify both. Those details are of course just a suggestion.

So, under "Otherwise"?

> Otherwise: two explicit priorities for insert/extract?
