### ISSUE TITLE
Use different Types of materials

### ISSUE THREAD

**Issue by WhiteBoi1211** [refinedmods/refinedstorage2#368]
### Describe your enhancement

I'd love to see the use of Maybe Copper and Gold!
Gold is used a little, but no one uses Copper. Since copper is a necessary part of Electronics, it would make sense to include it!
This would give Copper a use ingame since it's practically useless right now.

**Comment by raoulvdberge** [comment]
Nice idea! We discussed this on our discord earlier, and this is what we discussed:

I could make the cable recipe use copper, all other cable blocks (importer, exporter, etc) would then require copper as well since those other cable blocks require 1 cable in the recipe.

I'd introduce quartz enriched copper (same recipe as quartz enriched iron but with copper) and use that in the cable recipe.

Using it for cables would be "realistic" since the craft with glass imply they are fiber optic cable, but also does transfer power to the various part of the network.

**Comment by WhiteBoi1211** [comment]
Your idea sounds perfect, that would be an excellent way to introduce it!

I suggest using copper (or adding quartz-enriched gold) in some endgame machines, like the Crafter, etc. Since they are a bit more sophisticated than a grid, hence needing some more refined resources (which you have already done with the Processors, but why not expand on that!). That way it makes them a little more expensive, while still not being too much!

**Comment by raoulvdberge** [comment]
See #160
